# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""

# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

[character]
success_symbol = "[âœ](green)"
error_symbol = "[x](red)"

[directory]
read_only = " ó°Œ¾"
read_only_style = "red"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = '.../'
format = "[$path]($style)[$read_only]($read_only_style) "


[docker_context]
symbol = "ïŒˆ "

[git_branch]
style = "bold yellow"
symbol = "ï˜ "
truncation_length = 10
truncation_symbol = ".../"

[git_commit]
commit_hash_length = 4
tag_symbol = " ï’ "
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = 'â‡¡${count}'
style = "bold blue"
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
conflicted = 'ó°¨®'
stashed = 'ğŸ“¦ ${count}'
modified = "modified ${count}"

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol($version )]($style)"
style = "green"
detect_files = ["package.json", ".nvmrc", ".node-version", "pnpm-workspace.yaml"]
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx", "jsx", "vue"]
not_capable_style = "bold red"

[python]
symbol = "îˆµ "

# Output the command duration if over 2 seconds
[cmd_duration]
min_time = 2_000
format = "took [$duration ]($style)"
style = "bold white"
